### ISSUE TITLE
🐛 [BUG] - <No API Token found locally>

### ISSUE THREAD

**Issue by timwaale** [Loukious/StreamLabsTikTokStreamKeyGenerator#36]
### Description

Hi when I run the app and press load token, this is what pops up. Any ideas how to fix it?

### Reproduction steps

```bash
Press Load Token
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\tkinter\__init__.py", line 1921, in __call__
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\StreamLabsTikTokStreamKeyGenerator.py", line 159, in populate_token
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\StreamLabsTikTokStreamKeyGenerator.py", line 141, in fetch_online_token
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\TokenRetriever.py", line 60, in retrieve_token
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\undetected_chromedriver\__init__.py", line 372, in __init__
  File "C:\Users\Tim\AppData\Local\Temp\ONEFIL~1\selenium\webdriver\chromium\options.py", line 54, in binary_location
TypeError: Binary Location Must be a String
```

### OS

Windows

**Comment by Loukious** [comment]
You need to have Chrome installed and updated to the latest version.
