### ISSUE TITLE
🐛 [BUG] - Problem Setting TLOZ: EOW as game

### ISSUE THREAD

**Issue by JoEduardoReyes** [Loukious/StreamLabsTikTokStreamKeyGenerator#43]
### Description

Hola! Parece haber un error al momento de configurar The Legend of Zelda: Echoes of Wisdom como el juego del stream. Ya que este se configura como "otros". No encontré un error en la consola. Pero los otros juegos funcionan bien.

### Reproduction steps

```bash
1. Set up the live title.
2. Configure the game.
3. Start live.
```

### Screenshots

```bash
![SS taken from the streams and TIkTok Live Monitor](https://i.ibb.co/7tMkTYw/Captura-de-pantalla-2024-10-08-200231.png)
```

### Logs

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\requests\models.py", line 974, in json
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\json\__init__.py", line 346, in loads
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\json\decoder.py", line 337, in decode
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\tkinter\__init__.py", line 1921, in __call__
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\StreamLabsTikTokStreamKeyGenerator.py", line 280, in on_select
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\StreamLabsTikTokStreamKeyGenerator.py", line 83, in fetch_game_mask_id
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\Stream.py", line 16, in search
  File "C:\Users\joedu\AppData\Local\Temp\ONEFIL~2\requests\models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### OS

Windows

**Comment by SaintedWhisper** [comment]
Same with Sparking Zero, just getting

Traceback (most recent call last):
  File "C:\Users\NColl\AppData\Local\Temp\ON7531~1\tkinter\__init__.py", line 1921, in __call__
  File "C:\Users\NColl\AppData\Local\Temp\ON7531~1\StreamLabsTikTokStreamKeyGenerator.py", line 280, in on_select
  File "C:\Users\NColl\AppData\Local\Temp\ON7531~1\StreamLabsTikTokStreamKeyGenerator.py", line 83, in fetch_game_mask_id
  File "C:\Users\NColl\AppData\Local\Temp\ON7531~1\Stream.py", line 16, in search
  File "C:\Users\NColl\AppData\Local\Temp\ON7531~1\requests\models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
