### ISSUE TITLE
🐛 [BUG] - No webpage opening to login for API token

### ISSUE THREAD

**Issue by CBTcoding** [Loukious/StreamLabsTikTokStreamKeyGenerator#45]
### Description

I downloaded the release, extracted, launched, pressed load token and nothing happens.
I am using Microsoft Edge as a default browser.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
[screenshot](https://imgur.com/a/fCApaB1)
```

**Comment by Loukious** [comment]
You need chrome for this to function.

**Comment by CBTcoding** [comment]
I downloaded chrome, log in and i'm getting "Failed to obtain token." and failed to log in token online over and over, I also then downloaded Streamlabs and logged in to the TikTok to see if that helps but no luck.

I do have TikTok live access, is there any way I can get the token manually for the program?

**Comment by DarthMDev** [comment]
I have chrome and im still getting this with the latest version
`Error loading config file. Ignore this if it's the first time running the program or you never saved your config before.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/tmp/onefile_82608_1733456981_31468/tkinter/__init__.py", line 1921, in __call__
  File "/tmp/onefile_82608_1733456981_31468/StreamLabsTikTokStreamKeyGenerator.py", line 164, in populate_token
  File "/tmp/onefile_82608_1733456981_31468/StreamLabsTikTokStreamKeyGenerator.py", line 146, in fetch_online_token
  File "/tmp/onefile_82608_1733456981_31468/TokenRetriever.py", line 60, in retrieve_token
  File "/tmp/onefile_82608_1733456981_31468/seleniumwire/undetected_chromedriver/webdriver.py", line 32, in __init__
  File "/tmp/onefile_82608_1733456981_31468/seleniumwire/webdriver.py", line 41, in _setup_backend
  File "/tmp/onefile_82608_1733456981_31468/seleniumwire/backend.py", line 24, in create
  File "/tmp/onefile_82608_1733456981_31468/seleniumwire/server.py", line 28, in __init__
  File "/tmp/onefile_82608_1733456981_31468/seleniumwire/utils.py", line 159, in extract_cert_and_key
  File "/tmp/onefile_82608_1733456981_31468/pkgutil.py", line 639, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/onefile_82608_1733456981_31468/seleniumwire/ca.crt'
`
