### ISSUE TITLE
🐛 [BUG] - Browser does not open

### ISSUE THREAD

**Issue by CarmeloCampos** [Loukious/StreamLabsTikTokStreamKeyGenerator#50]
### Description

Selenium does not detect my chrome? It would be nice to be able to manually select my chrome PATH.

### Reproduction steps

```bash
1. Click on 'Load token'
2. Close program
```

### Screenshots

```bash
![Console error](https://i.imgur.com/p1Nsb2V.png)
![Error after closing the program](https://i.imgur.com/PaXfnd0.png)
```

### Logs

```bash
./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
Error loading config file. Ignore this if it's the first time running the program or you never saved the config file before.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/tmp/onefile_41465_1730416848_40545/tkinter/__init__.py", line 1921, in __call__
  File "/tmp/onefile_41465_1730416848_40545/StreamLabsTikTokStreamKeyGenerator.py", line 159, in populate_token
  File "/tmp/onefile_41465_1730416848_40545/StreamLabsTikTokStreamKeyGenerator.py", line 141, in fetch_online_token
  File "/tmp/onefile_41465_1730416848_40545/TokenRetriever.py", line 60, in retrieve_token
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/undetected_chromedriver/webdriver.py", line 32, in __init__
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/webdriver.py", line 41, in _setup_backend
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/backend.py", line 24, in create
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/server.py", line 28, in __init__
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/utils.py", line 159, in extract_cert_and_key
  File "/tmp/onefile_41465_1730416848_40545/pkgutil.py", line 639, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/onefile_41465_1730416848_40545/seleniumwire/ca.crt'









Exception ignored in: <compiled_function Chrome.__del__ at 0x70e6b5b9a890>
Traceback (most recent call last):
  File "/tmp/onefile_41465_1730416848_40545/undetected_chromedriver/__init__.py", line 843, in __del__
  File "/tmp/onefile_41465_1730416848_40545/seleniumwire/webdriver.py", line 67, in quit
  File "/tmp/onefile_41465_1730416848_40545/undetected_chromedriver/__init__.py", line 806, in __getattribute__
AttributeError: 'Chrome' object has no attribute 'backend'
```

### OS

Linux

**Comment by GordosFunkos** [comment]
You already uninstalled and installed chrome? I know this might've been a first solution, but you never know

**Comment by Loukious** [comment]
You probably have an older version. You need to latest. Check for updates.
