### ISSUE TITLE
🐛 [BUG] - Error loading config file.

### ISSUE THREAD

**Issue by BlueDragon4251** [Loukious/StreamLabsTikTokStreamKeyGenerator#59]
### Description

When i try to load the token but haven`t installed streamlabs i see the error given in the logs

### Reproduction steps

```bash
1. Open the EXE
2. Load Token
3. No API Token found locally. A webpage will now open to
allow you to login into your TikTok account - click on ok
4. See error
```

### Screenshots

```bash
![image](https://github.com/user-attachments/assets/b6d17277-716e-48c5-b903-5e90c5835d86)
![image](https://github.com/user-attachments/assets/f1863bc9-9688-4165-9cea-14d69421cea8)
```

### Logs

```bash
Error loading config file. Ignore this if it's the first time running the program or you never saved your config before.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\tkinter\__init__.py", line 1921, in __call__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\StreamLabsTikTokStreamKeyGenerator.py", line 164, in populate_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\StreamLabsTikTokStreamKeyGenerator.py", line 146, in fetch_online_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\TokenRetriever.py", line 60, in retrieve_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\undetected_chromedriver\__init__.py", line 372, in __init__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\selenium\webdriver\chromium\options.py", line 54, in binary_location
TypeError: Binary Location Must be a String
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\tkinter\__init__.py", line 1921, in __call__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\StreamLabsTikTokStreamKeyGenerator.py", line 164, in populate_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\StreamLabsTikTokStreamKeyGenerator.py", line 146, in fetch_online_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\TokenRetriever.py", line 60, in retrieve_token
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\undetected_chromedriver\__init__.py", line 372, in __init__
  File "C:\Users\evoly\AppData\Local\Temp\ONEFIL~3\selenium\webdriver\chromium\options.py", line 54, in binary_location
TypeError: Binary Location Must be a String
```

### OS

Windows

**Comment by Loukious** [comment]
You need Chrome installed.
